'use client'

import {useMemo,useState} from 'react'
import {ArrowDownToLine,ArrowUpFromLine,Check,ExternalLink,ShieldCheck,Tag,WalletCards,X} from 'lucide-react'
import {events,classes} from '@/mock/data'
import {TicketAsset} from '@/types'
import {useAppStore} from '@/stores/app'

export default function Portfolio(){
  const {assets,points,updateAssetStatus,showToast}=useAppStore()
  const [tab,setTab]=useState('assets')
  const [selling,setSelling]=useState<TicketAsset|null>(null)
  const [price,setPrice]=useState('')
  const total=useMemo(()=>assets.reduce((sum,asset)=>sum+asset.marketPrice,0),[assets])
  const listed=assets.filter(asset=>asset.status==='listed').length
  const openSell=(asset:TicketAsset)=>{setSelling(asset);setPrice(String(asset.marketPrice))}
  const confirmSell=()=>{if(!selling||!Number(price))return;updateAssetStatus(selling.id,'listed');setSelling(null);showToast(`Ticket listed at $${price}`,'success')}
  const cancelListing=(asset:TicketAsset)=>{updateAssetStatus(asset.id,'owned');showToast('Listing cancelled')}
  return <div className="content portfolio-page">
    <div className="page-heading"><div><div className="eyebrow">YOUR COLLECTION</div><h1 className="title">Portfolio</h1><p className="subtitle">Manage verified ticket assets, balances and market activity.</p></div><div className="wallet-pill"><span className="status-dot"/>Wallet connected <strong>0x8B7...93A1</strong></div></div>
    <section className="portfolio-overview"><div className="portfolio-primary"><span>Total portfolio value</span><strong>${total.toLocaleString(undefined,{minimumFractionDigits:2})}</strong><small>+$184.20 <b>8.4%</b> this month</small></div><div className="portfolio-stat"><span>Available balance</span><strong>$1,980.00</strong><small>USDC on Polygon</small></div><div className="portfolio-stat"><span>Active listings</span><strong>{listed}</strong><small>{assets.length-listed} tickets held</small></div><div className="portfolio-stat"><span>Rewards</span><strong>{points.toLocaleString()} PXT</strong><small>Gold member</small></div></section>
    <section className="section"><div className="portfolio-actions"><div className="tabs"><button className={`tab ${tab==='assets'?'active':''}`} onClick={()=>setTab('assets')}>Ticket assets <span>{assets.length}</span></button><button className={`tab ${tab==='history'?'active':''}`} onClick={()=>setTab('history')}>Activity</button></div><div className="actions"><button className="btn secondary" onClick={()=>showToast('Deposit flow opened in demo mode')}><ArrowDownToLine size={14}/> Deposit</button><button className="btn secondary" onClick={()=>showToast('Withdraw flow opened in demo mode')}><ArrowUpFromLine size={14}/> Withdraw</button></div></div>
      {tab==='assets'?<div className="asset-table"><div className="asset-head"><span>Event</span><span>Ticket details</span><span>Market value</span><span>Verification</span><span/></div>{assets.map(asset=>{const event=events.find(item=>item.id===asset.eventId)!;const ticketClass=classes.find(item=>item.id===asset.ticketClassId)!;return <article className="asset-row" key={asset.id}><div className="asset-event"><span style={{backgroundImage:`url(${event.cover})`}}/><div><strong>{event.name}</strong><small>{event.city} · {new Date(event.startAt).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</small></div></div><div className="asset-seat"><span className="badge">{ticketClass.name}</span><strong>{asset.section} · Row {asset.row} · Seat {asset.seat}</strong><small>Mobile ticket</small></div><div className="asset-value"><strong>${asset.marketPrice}</strong><small>Face value ${asset.officialPrice}</small></div><div className="asset-verification"><span><ShieldCheck size={14}/> On-chain verified</span><small>Token #{asset.id.replace('asset-','10')}</small></div><div className="asset-action"><span className={`status ${asset.status}`}>{asset.status==='listed'?'Listed for sale':'In wallet'}</span><button className="btn secondary" onClick={()=>asset.status==='listed'?cancelListing(asset):openSell(asset)}>{asset.status==='listed'?'Cancel':'Sell'}</button></div></article>})}</div>:<div className="activity-timeline">{['Purchase completed · BLACKPINK CAT1','Ownership verified on Polygon','Ticket Pool draw settled · VIP2','Listing created · F1 Singapore'].map((item,index)=><div key={item}><span className={index===0?'success':''}>{index===0?<Check size={14}/>:<ExternalLink size={13}/>}</span><p><strong>{item}</strong><small>{index+1} hour{index?'s':''} ago · Transaction confirmed</small></p></div>)}</div>}
    </section>
    <div className="security-note"><WalletCards size={18}/><span><strong>Non-custodial settlement</strong><small>Your ticket assets remain in your wallet until a sale is matched. Payment is protected by escrow.</small></span><ShieldCheck size={18}/></div>
    {selling&&<div className="dialog-overlay" onMouseDown={event=>event.currentTarget===event.target&&setSelling(null)}><div className="dialog-panel sell-dialog"><button className="icon-btn dialog-close" onClick={()=>setSelling(null)} aria-label="Close"><X size={17}/></button><div className="dialog-icon"><Tag size={19}/></div><div className="eyebrow">CREATE LISTING</div><h2>Set your asking price</h2><p className="muted">{events.find(item=>item.id===selling.eventId)?.name} · Section {selling.section}</p><label className="price-field"><span>Listing price</span><div><b>$</b><input autoFocus inputMode="numeric" value={price} onChange={event=>setPrice(event.target.value.replace(/[^0-9]/g,''))}/><small>USD</small></div></label><div className="pricing-guidance"><div><span>Market floor</span><strong>${selling.marketPrice}</strong></div><div><span>Face value</span><strong>${selling.officialPrice}</strong></div><div><span>You receive</span><strong>${Math.max(0,Number(price||0)*.95).toFixed(2)}</strong></div></div><div className="fee-note"><ShieldCheck size={15}/> 5% seller fee. Asset transfers only after payment clears.</div><button className="btn primary dialog-submit" disabled={!Number(price)} onClick={confirmSell}>List ticket for ${price||'0'}</button></div></div>}
  </div>
}
