'use client'

import {useMemo,useState} from 'react'
import {ArrowUpRight,BarChart3,Check,ChevronDown,PackagePlus,Plus,RefreshCw,ShieldCheck,SlidersHorizontal,UploadCloud} from 'lucide-react'
import {assets,classes,events,pools} from '@/mock/data'
import {useAppStore} from '@/stores/app'

export default function SellerStudio(){
  const {showToast}=useAppStore(); const [tab,setTab]=useState<'overview'|'inventory'|'listings'|'pools'>('overview'); const [selected,setSelected]=useState<string[]>([])
  const inventory=useMemo(()=>assets.slice(0,6),[])
  const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])
  return <div className="content seller-page">
    <div className="page-heading"><div><div className="eyebrow">PROFESSIONAL SELLER · LEVEL 3</div><h1 className="title">Seller Studio</h1><p className="subtitle">Manage inventory, pricing and pool supply from one operating desk.</p></div><div className="seller-verification"><ShieldCheck size={16}/><span><strong>Verified seller</strong><small>98.7% successful delivery</small></span></div></div>
    <nav className="studio-tabs" aria-label="Seller studio sections">{[['overview','Overview'],['inventory','Inventory'],['listings','Listings'],['pools','Pools']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id as typeof tab)}>{label}</button>)}</nav>
    {tab==='overview'&&<><section className="seller-metrics"><div><span>Gross sales · 30d</span><strong>$48,290</strong><small className="positive">+18.4% vs last month</small></div><div><span>Inventory value</span><strong>$126,480</strong><small>214 verified assets</small></div><div><span>Pending settlement</span><strong>$8,420</strong><small>12 orders in reserve</small></div><div><span>Sell-through rate</span><strong>76.8%</strong><small>Across 18 events</small></div></section><section className="section seller-dashboard-grid"><div className="plain-panel"><div className="section-head"><div><h2>Sales performance</h2><span className="small muted">Last 30 days</span></div><button className="icon-btn" onClick={()=>showToast('Chart range changed')} aria-label="Change range"><ChevronDown size={15}/></button></div><div className="seller-chart">{[38,44,40,52,48,58,55,62,69,64,78,72,86,80,92].map((height,i)=><i key={i} style={{height:`${height}%`}}/>)}</div><div className="row small muted"><span>Aug 24</span><span>Sep 22</span></div></div><div className="plain-panel seller-actions-panel"><div className="section-head"><h2>Quick actions</h2><SlidersHorizontal size={16}/></div><button onClick={()=>setTab('inventory')}><PackagePlus size={17}/><span><strong>Import inventory</strong><small>Upload a CSV or add tickets manually</small></span><ArrowUpRight size={15}/></button><button onClick={()=>showToast('Bulk pricing editor opened')}><RefreshCw size={17}/><span><strong>Adjust pricing</strong><small>Update selected assets by price rule</small></span><ArrowUpRight size={15}/></button><button onClick={()=>setTab('pools')}><Plus size={17}/><span><strong>Create a Ticket Pool</strong><small>Turn locked inventory into draw supply</small></span><ArrowUpRight size={15}/></button></div></section><section className="section"><div className="section-head"><div><h2>Top markets</h2><p className="small muted">Where your inventory is moving fastest.</p></div><button className="text-button" onClick={()=>setTab('analytics' as typeof tab)}>View analytics</button></div><div className="seller-market-list">{events.slice(0,4).map((event,i)=><div key={event.id}><span className="market-art" style={{backgroundImage:`url(${event.cover})`}}/><span><strong>{event.name}</strong><small>{event.city} · {classes.filter(c=>c.eventId===event.id).length*8} active assets</small></span><b>${[12840,9820,7640,5380][i].toLocaleString()}</b><span className="positive">+{[24,18,12,8][i]}%</span></div>)}</div></section></>}
    {tab==='inventory'&&<section className="seller-section"><div className="seller-toolbar"><button className="btn primary" onClick={()=>showToast('CSV import opened')}><UploadCloud size={15}/> Import CSV</button><button className="btn secondary" onClick={()=>showToast('New ticket form opened')}><Plus size={15}/> Add ticket</button><span className="small muted">{selected.length} selected</span><button className="btn secondary" disabled={!selected.length} onClick={()=>showToast('Bulk price editor opened')}>Bulk price</button></div><div className="seller-table"><div className="seller-table-head"><span>Asset</span><span>Event / class</span><span>Current value</span><span>Status</span><span/></div>{inventory.map(asset=>{const event=events.find(e=>e.id===asset.eventId)!;const ticket=classes.find(c=>c.id===asset.ticketClassId)!;return <div className="seller-table-row" key={asset.id}><label><input type="checkbox" checked={selected.includes(asset.id)} onChange={()=>toggle(asset.id)}/><span className="market-art" style={{backgroundImage:`url(${event.cover})`}}/></label><span><strong>{event.name}</strong><small>{ticket.name} · Section {asset.section} · Row {asset.row}</small></span><strong>${asset.marketPrice}</strong><span className="status owned">Verified</span><button className="text-button" onClick={()=>showToast(`Pricing editor opened for ${ticket.name}`)}>Edit</button></div>})}</div></section>}
    {tab==='listings'&&<section className="seller-section"><div className="section-head"><div><h2>Active listings</h2><p className="small muted">Prices are visible in the public marketplace.</p></div><button className="btn secondary" onClick={()=>showToast('Listing rules opened')}>Listing rules</button></div><div className="seller-listing-grid">{inventory.slice(0,4).map((asset,i)=>{const event=events.find(e=>e.id===asset.eventId)!;return <article key={asset.id}><div className="listing-banner" style={{backgroundImage:`url(${event.cover})`}}/><div className="card-body"><div className="row"><span className="badge">{i%2?'CAT1':'VIP1'}</span><span className="positive small">Live</span></div><strong>{event.name}</strong><small>{event.city} · Section {asset.section}</small><div className="row listing-bottom"><b>${asset.marketPrice+i*16}</b><button className="text-button" onClick={()=>showToast('Listing edited')}>Edit</button></div></div></article>})}</div></section>}
    {tab==='pools'&&<section className="seller-section"><div className="seller-toolbar"><button className="btn primary" onClick={()=>showToast('Pool creation wizard opened')}><Plus size={15}/> Create pool</button><span className="small muted">{pools.length} pools · {pools.reduce((sum,p)=>sum+p.remainingTickets,0).toLocaleString()} tickets available</span></div><div className="seller-pool-list">{pools.slice(0,4).map(pool=><div key={pool.id}><span className="market-art" style={{backgroundImage:`url(${pool.cover})`}}/><span><strong>{pool.name}</strong><small>{pool.remainingTickets} remaining · closes {new Date(pool.closeAt).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</small></span><span><small>Draw</small><b>${pool.drawPrice}</b></span><span><small>NAV</small><b>${pool.nav.toLocaleString()}</b></span><span className="status owned">Active</span><button className="text-button" onClick={()=>showToast('Pool editor opened')}>Manage</button></div>)}</div></section>}
  </div>
}
